// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4WbXUMo0wV1I9F0RQe-Mw9pTNHSnm9c',
    appId: '1:210431484744:web:68da616cc35329d043897d',
    messagingSenderId: '210431484744',
    projectId: 'fluttercomments',
    authDomain: 'fluttercomments.firebaseapp.com',
    storageBucket: 'fluttercomments.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtXud7DokiJiX-Sku-HsEH7tvKNwkFmo',
    appId: '1:210431484744:android:f58306e07fa17a0643897d',
    messagingSenderId: '210431484744',
    projectId: 'fluttercomments',
    storageBucket: 'fluttercomments.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeuBoRDNYzlu0_aUaBejEKAwel6hdTZM',
    appId: '1:210431484744:ios:671be646b1533bf543897d',
    messagingSenderId: '210431484744',
    projectId: 'fluttercomments',
    storageBucket: 'fluttercomments.appspot.com',
    iosBundleId: 'com.example.comments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeuBoRDNYzlu0_aUaBejEKAwel6hdTZM',
    appId: '1:210431484744:ios:671be646b1533bf543897d',
    messagingSenderId: '210431484744',
    projectId: 'fluttercomments',
    storageBucket: 'fluttercomments.appspot.com',
    iosBundleId: 'com.example.comments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl4WbXUMo0wV1I9F0RQe-Mw9pTNHSnm9c',
    appId: '1:210431484744:web:9e1568af483c74b743897d',
    messagingSenderId: '210431484744',
    projectId: 'fluttercomments',
    authDomain: 'fluttercomments.firebaseapp.com',
    storageBucket: 'fluttercomments.appspot.com',
  );
}
